CRUD/Python-Django/product/urls.py
from django.conf.urls import url
from product import views
from product.views import ViewAddProduct, ViewEditProduct

urlpatterns = [
    url(r'^addproduct/$', ViewAddProduct.as_view(), name="add_product"),
    url(r'^product/(?P<product_id>\d+)$', views.show_product, name='show_product'),
    url(r'^removeProduct/(?P<product_id>\d+)$', views.remove_product, name='remove_product'),
    url(r'^editproduct/(?P<product_id>\d+)$', ViewEditProduct.as_view(), name='edit_product'),
    url(r'^manageproduct/$', views.manage_products, name='manageproduct'),
]

CRUD/Python-Django/sale/urls.py
from django.conf.urls import url
from sale import views
from sale.views import ViewSellProduct, ViewEditSale

urlpatterns = [
    url(r'^sellProduct/$', ViewSellProduct.as_view(), name="sell_product"),
    url(r'^sale/(?P<sale_id>\d+)$', views.show_sale, name='show_sale'),
    url(r'^removesale/(?P<sale_id>\d+)$', views.remove_sale, name='remove_sale'),
    url(r'^editsale/(?P<sale_id>\d+)$', ViewEditSale.as_view(), name='edit_sale'),
    url(r'^managesales/$', views.manage_sales, name='manage_sales'),
]

CRUD/Python-Django/product/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, null=False)

class Product(models.Model):
    name = models.CharField(max_length=255, null=False)
    expiration = models.DateField(auto_now=True, null=False)
    price = models.FloatField(null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

CRUD/Python-Django/product/forms.py
from django import forms


class frm_add_product(forms.Form):
    name = forms.CharField(required=True)
    expiration = forms.CharField(required=True)
    price = forms.FloatField(required=True)

    def is_valid(self):
        valid = True
        if not super(frm_add_product, self).is_valid():
            self.validation_add_error('Por favor, verifique os dados informados')
            valid = False
        return valid

    def validation_add_error(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

CRUD/Python-Django/product/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View

from product.forms import frm_add_product
from product.models import Product
from product.models import Category
from user_profile.models import user_profile


## GoTos ##
##these functions send the user to some page##
@login_required
def add_product(request):
    return render(request, 'add_product.html', {'logged_profile': get_logged_user(request)})


@login_required
def manage_products(request):
    return render(request, 'manage_products.html',
                  {'products': Product.objects.all(), 'logged_profile': get_logged_user(request)})


@login_required
def show_product(request, product_id):
    product = Product.objects.get(id=product_id)
    return render(request, 'show_product.html', {'logged_profile': get_logged_user(request), 'product': product})


##forms##

class ViewAddProduct(View):
    template_name = 'add_product.html'

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        return render(request, self.template_name, {'categories': categories})

    def post(self, request, *args, **kwargs):
        form = frm_add_product(request.POST)

        if form.is_valid():
            dados_form = form.data

            category = Category.objects.get(id=dados_form['category_selected'])

            product = Product(
                name=dados_form['name'],
                expiration=dados_form['expiration'],
                price=dados_form['price'],
                category=category
            )

            product.save()

            return redirect('manageproduct')

        return render(request, self.template_name, {'form': form})


class ViewEditProduct(View):
    template_name = 'edit_product.html'

    def get(self, request, *args, **kwargs):
        categories = Category.objects.all()
        product = Product.objects.get(id=kwargs['product_id'])
        return render(request, self.template_name, {'categories': categories, 'product': product})

    def post(self, request, *args, **kwargs):
        form = frm_add_product(request.POST)

        if form.is_valid():
            dados_form = form.data

            category = Category.objects.get(id=dados_form['category_selected'])

            product = Product(
                id=kwargs['product_id'],
                name=dados_form['name'],
                expiration=dados_form['expiration'],
                price=dados_form['price'],
                category=category
            )

            product.save()

            return redirect('manageproduct')

        return render(request, self.template_name, {'form': form})


@login_required()
def remove_product(request, product_id):
    product = Product.objects.get(id=product_id)
    product.delete()
    return redirect('manageproduct')


##auxiliary functions
def get_logged_user(request):
    return request.user.user_profile

CRUD/Python-Django/product/templates/add_product.html
{% extends "base.html" %}

{% block body %}

<form class="form-signin" role="form" action="{% url 'add_product' %}" method="post">

    {% csrf_token %}

    <h2 class="form-signin-heading">Criar novo produto</h2>

    <input type="text" id="id_name" name="name" class="form-control"
        placeholder="Nome do produto *" required autofocus>

    <input type="date" id="id_expiration" name="expiration" class="form-control"
        placeholder="Expiração *" required >

    <input type="text" id="id_price" name="price" class="form-control"
        placeholder="Preço *" required >

    <select class="form-control" name="category_selected" id="category_selected">
        {% for category in categories %}
            <option value="{{category.id}}">{{category.name}}</option>
        {% endfor %}
    </select>

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Add product">
        Add product
    </button>

    <hr/>

    {% if form.errors %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
            </button>
            {{form.non_field_errors}}
        </div>
    {% endif %}

</form>

{% endblock %}

CRUD/Python-Django/product/templates/edit_product.html
{% extends "base.html" %}

{% block body %}

<form class="form-signin" role="form" action="{% url 'edit_product' product.id%}" method="post">

    {% csrf_token %}

    <h2 class="form-signin-heading">Editar novo produto</h2>

    <input type="text" id="id_name" name="name" class="form-control" value="{{ product.name }}"
        placeholder="Nome do produto *" required autofocus>

    <input type="date" id="id_expiration" name="expiration" class="form-control" value="{{ product.expiration|date:"Y-m-d" }}"
        placeholder="Expiração *" required >

    <input type="text" id="id_price" name="price" class="form-control" value="{{ product.price }}"
        placeholder="Preço *" required >

    <select class="form-control" name="category_selected" id="category_selected">
        {% for category in categories %}
            {% if product.category == category%}
                <option selected value="{{category.id}}">{{category.name}}</option>
            {% else %}
                <option value="{{category.id}}">{{category.name}}</option>
            {% endif %}
        {% endfor %}
    </select>

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Save changes">
        Save Changes
    </button>

    <hr/>

    {% if form.errors %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
            </button>
            {{form.non_field_errors}}
        </div>
    {% endif %}

</form>

{% endblock %}

CRUD/Python-Django/product/templates/manage_products.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os Perfis</strong>
		</div>
		{% if products %}
			    <table class="table table-bordered table-hover">
                    <thead>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Expiration</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th>Actions</th>
                    </thead>

                    {% for prd in products %}
                        <tr>
                            <td>{{ prd.id }}</td>
                            <td>{{ prd.name }}</td>
                            <td> {{ prd.expiration }}</td>
                            <td> R${{ prd.price }}</td>
                            <td> {{ prd.category.name }}</td>
                            <td>
                                <a href="{% url 'remove_product' prd.id %}">
                                    <span class="glyphicon glyphicon-trash"/>
                                </a>
                                <a href="{% url 'edit_product' prd.id %}">
                                    <span class="glyphicon glyphicon-pencil"/>
                                </a>
                            </td>
                        </tr>
				    {% endfor %}
                </table>
		{% else %}
			<p>Nenhum produto encontrado</p>
		{% endif %}
	</div>
    <a class="btn btn-primary" href="{% url 'add_product' %}">Novo Produto</a>
</div>
{% endblock %}

CRUD/Python-Django/product/templates/show_product.html
{% extends "base.html" %}
{% block body %}
<div class="row">
	<div class="col-lg-12">
		<h2>{{product.name}}</h2>
		<div>
			<div>Expiration date: {{product.expiration}}</div>
			<div class="alert alert-success">Price: R${{product.price}}"</div>
		</div>
	</div>
</div>
{% endblock %}	