CRUD/Python-Django/sale/urls.py
from django.conf.urls import url
from sale import views
from sale.views import ViewSellProduct, ViewEditSale

urlpatterns = [
    url(r'^sellProduct/$', ViewSellProduct.as_view(), name="sell_product"),
    url(r'^sale/(?P<sale_id>\d+)$', views.show_sale, name='show_sale'),
    url(r'^removesale/(?P<sale_id>\d+)$', views.remove_sale, name='remove_sale'),
    url(r'^editsale/(?P<sale_id>\d+)$', ViewEditSale.as_view(), name='edit_sale'),
    url(r'^managesales/$', views.manage_sales, name='manage_sales'),
]

CRUD/Python-Django/user_account/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout_then_login
from user_account.views import register_user_view

urlpatterns = [
    url(r'^register/$', register_user_view.as_view(), name="register"),
    url(r'^login/$', login ,{'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, {'login_url':'/login/'}, name='logout')
]

CRUD/Python-Django/user_account/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

CRUD/Python-Django/product/forms.py
from django import forms


class frm_add_product(forms.Form):
    name = forms.CharField(required=True)
    expiration = forms.CharField(required=True)
    price = forms.FloatField(required=True)

    def is_valid(self):
        valid = True
        if not super(frm_add_product, self).is_valid():
            self.validation_add_error('Por favor, verifique os dados informados')
            valid = False
        return valid

    def validation_add_error(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

CRUD/Python-Django/user_account/forms.py
from django import forms
from django.contrib.auth.models import User


class frm_register_user(forms.Form):
    username = forms.CharField(required=True)
    fullname = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True)
    phone = forms.CharField(required=True)

    def is_valid(self):

        valid = True

        if not super(frm_register_user, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        user_exists = User.objects.filter(username=self.data['username']).exists()

        if user_exists:
            self.adiciona_erro('Usuario ja existente')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

CRUD/Python-Django/user_account/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render

# Create your views here.

from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth.models import User
from django.views.generic.base import View
from user_profile.models import user_profile
from user_account.forms import frm_register_user


class register_user_view(View):
    template_name = 'register.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        form = frm_register_user(request.POST)

        if form.is_valid():
            dados_form = form.data

            usuario = User.objects.create_user(dados_form['username'],
                                               dados_form['email'], dados_form['password'])

            perfil = user_profile(
                            username=dados_form['username'],
                            fullname=dados_form['fullname'],
                            email=dados_form['email'],
                            phone=dados_form['phone'],
                            user=usuario)

            perfil.save()

            return redirect('index')

        return render(request, self.template_name, {'form': form})

CRUD/Python-Django/user_account/templates/base_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>LearnToImplement - Sales</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/signin.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            {% block body %}
            {% endblock %} 
        </div>
        <script src="{% static "scripts/vendor/bootstrap-min.js" %}"></script>
    </body>
</html>

CRUD/Python-Django/user_account/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" 
        action="{% url 'login' %}" method="post">

        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" 
            placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" 
            placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">
            Login
        </button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                    &times;
                </button>
                Por favor, verifique o Email e/ou Senha informados
            </div>
        {% endif %}

        <a class="btn btn-lg btn-default btn-block" style="margin-top:10px"href="{% url 'register' %}">registre-se</a>
        
    </form>

{% endblock %}

CRUD/Python-Django/user_account/templates/register.html
{% extends "base_usuario.html" %}

{% block body %}

<form class="form-signin" role="form" action="{% url 'register' %}" method="post">

    {% csrf_token %}

    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control" 
        placeholder="Email *" required autofocus>

    <input type="text" id="id_username" name="username" class="form-control"
        placeholder="username" required >

    <input type="text" id="id_name" name="fullname" class="form-control"
        placeholder="Name *" required >

    <input type="password" id="id_password" name="password" class="form-control"
        placeholder="Password *" required>

    <hr />

    <input type="text" id="id_phone" name="phone" class="form-control"
        placeholder="phone">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Register">
        Register
    </button>

    <hr/>

    {% if form.errors %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                &times;
            </button>
            {{form.non_field_errors}}
        </div>
    {% endif %}

</form>

{% endblock %}